version: '3.3'
services:
  po-task-queue:
    container_name: po-task-queue
    image: rabbitmq:3.8-rc-management-alpine
    ports:
     - "15672:15672"
     - "5672:5672"
    env_file:
     - .env
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=password
  po-database:
    container_name: po-database
    image: mongo:latest
    env_file:
     - .env
    ports:
     - "27017:27017"
    volumes:
     - mongo_data_vol:/data/db
  po-api:
    build: ./backend
    container_name: po-api
    env_file:
     - .env
    entrypoint:
     - python
     - start_server.py
    ports:
     - "5000:5000"
  po-celery:
    build: ./backend
    container_name: po-celery
    env_file:
     - .env
    entrypoint:
     - celery
     - -A
     - server     
     - worker
     - --app=server.app:celery
     - --loglevel=info
volumes:
  mongo_data_vol:
