version: '3.3'
services:  
  po-api:
    container_name: po-api
    image: po-backend
    build: ./backend
    env_file:
     - .env
     - overrides.env
    volumes:
     - ./backend:/opt/portfolio-optimizer
    entrypoint:
     - python
     - start_server.py
    ports:
     - "5000:5000"
  po-processor:
    container_name: po-processor
    image: po-backend
    build: ./backend
    env_file:
     - .env
     - overrides.env
    volumes:
     - ./backend:/opt/portfolio-optimizer
    entrypoint:
     - python
     - processor.py
  po-celery:
    container_name: po-celery
    image: po-backend
    build: ./backend
    env_file:
     - .env
     - overrides.env
    volumes:
     - ./backend:/opt/portfolio-optimizer
    entrypoint:
     - celery
     - -A
     - server     
     - worker
     - --app=server.app:celery
     - --loglevel=info  
  po-build-ui:
    container_name: po-build-ui
    image: po-frontend
    build: ./frontend
    volumes:
     - ./frontend/src/:/opt/portfolio-optimizer/src
     - ./frontend/static-html/:/opt/portfolio-optimizer/static-html
     - ./frontend/package.json:/opt/portfolio-optimizer/package.json
     - html_vol:/html
    env_file:
     - .env
     - overrides.env
    entrypoint:
     - npm
     - run
     - build-docker
  po-task-queue:
    container_name: po-task-queue
    image: rabbitmq:3.8-rc-management-alpine
    ports:
     - "15672:15672"
     - "5672:5672"
    env_file:
     - .env
     - overrides.env
    environment:
     - RABBITMQ_DEFAULT_USER=admin
  po-database:
    container_name: po-database
    image: mongo:latest
    env_file:
     - .env
     - overrides.env
    ports:
     - "27017:27017"
    volumes:
     - mongo_data_vol:/data/db
  po-gateway:
    container_name: po-gateway
    image: nginx:latest
    ports:
     - "80:80"
     - "443:443"
    volumes: 
     - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
     - html_vol:/etc/nginx/html
    env_file:
     - .env
     - overrides.env
volumes:
  mongo_data_vol:
  html_vol:
